vti_encoding:SR|utf8-nl
vti_author:SR|APOLLO\\michaelm
vti_modifiedby:SR|APOLLO\\michaelm
vti_timelastmodified:TR|13 Oct 2011 04:52:16 -0000
vti_timecreated:TR|13 Oct 2011 04:50:45 -0000
vti_lineageid:SR|{6DF19352-FC09-4131-B69C-C8EA67595946}
vti_extenderversion:SR|5.0.2.6790
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TW|13 Oct 2011 04:50:45 -0000
vti_cacheddtm:TX|13 Oct 2011 04:52:16 -0000
vti_filesize:IR|6563
vti_syncwith_advantage.rate-monitor.com\:80:TR|13 Oct 2011 04:52:16 -0000
vti_syncwith_hercules.rate-monitor.com\:80:TR|13 Oct 2011 04:52:16 -0000
vti_syncwith_pastreports.rate-monitor.com\:80:TR|13 Oct 2011 04:52:16 -0000
vti_syncwith_siflv.rate-monitor.com\:80:TX|13 Oct 2011 04:52:16 -0000
vti_syncofs_siflv.rate-monitor.com\:80:TW|02 Sep 2014 16:41:28 -0000
vti_syncwith_rmlitelv.rate-monitor.com\:80:TX|13 Oct 2011 04:52:16 -0000
vti_syncofs_rmlitelv.rate-monitor.com\:80:TW|03 Sep 2014 18:55:01 -0000
vti_syncofs_localhost\\c\:\\users\\dennis mallonee\\documents\\my web sites\\websites\\www.rate-monitor.com/c\:/users/dennis mallonee/documents/my web sites/websites/www.rate-monitor.com:TW|04 Sep 2014 13:23:19 -0000
vti_syncwith_localhost\\c\:\\users\\dennis mallonee\\documents\\my web sites\\websites\\www.rate-monitor.com/c\:/users/dennis mallonee/documents/my web sites/websites/www.rate-monitor.com:TX|13 Oct 2011 04:52:16 -0000
vti_syncwith_localhost\\d\:\\websites\\rmlite.rate-monitor.com/d\:/websites/rmlite.rate-monitor.com:TX|13 Oct 2011 04:52:16 -0000
vti_syncofs_localhost\\d\:\\websites\\rmlite.rate-monitor.com/d\:/websites/rmlite.rate-monitor.com:TW|04 Sep 2014 13:59:29 -0000
